- title: GeoDEN
  group: featured #remove this for non-featured products
  subtitle: Visual Analytics
  image: images/product-images/geoden.jpg
  link: https://github.com/geohai/GeoDEN
  description: GeoDEN is a visual analytics tool for exploratory analysis of spatiotemporal spread and interaction of dengue serotypes.
  repo: geohai/GeoDEN
  tags:
    - software
    - website
