# Morteza Karimzadeh ##############################################
#2026
#foundation model Genealogy 
- id: doi:10.1145/3789505
  type: journal
  image: 
  buttons:
    - type: preprint
      text: preprint
      link: https://arxiv.org/abs/2504.17177
  tags:
    - foundation model
    - remote sensing
    - representation learning
    - machine learning

#2025
# PM and location encoding
- id: doi:10.1080/15481603.2025.2594797 
  image: https://res.cloudinary.com/dz3zgmhnr/image/upload/v1750457206/2021-07-05_pred_geoclip_with_boundary_cropped-min-min_r0z2yv.png
  type: journal
  buttons:
    - type: source
      text: Repo
      link: https://github.com/geohai/pm25-geolocation
    - type: preprint
      text: preprint
      link: https://arxiv.org/abs/2505.18461
  tags:
    - spatiotemporal
    - machine learning
    - remote sensing
    - public health
    - air pollution
    - foundation model
    - earth embeddings

# copd exacerbations
- id: doi:10.1101/2025.05.27.25328449
  image: https://res.cloudinary.com/dz3zgmhnr/image/upload/v1770666142/fdf684b2-8edd-495d-b73c-954b1a3d5142.png
  type: journal
  buttons:
    - type: preprint
      text: preprint
      link: https://pmc.ncbi.nlm.nih.gov/articles/PMC12148289/
  tags:
    - spatiotemporal
    - public health
    - air pollution
    - earth embeddings


 #COVID LSTM hospitalization 
- id: doi:10.1080/13658816.2025.2527266 
  image: https://res.cloudinary.com/dz3zgmhnr/image/upload/v1770666335/65a39881-347c-4e94-83d8-0527a9fbdaf8.png
  type: journal
  buttons:
    - type: source
      text: Repo
      link: https://github.com/geohai/covid-lstm-hosp
    - type: preprint
      text: preprint
      link: https://arxiv.org/abs/2506.05752
  tags:
    - spatiotemporal
    - machine learning
    - covid-19
    - public health
    - epidemiology


#autoice fusion
- id: doi:10.1109/IGARSS55030.2025.11243075
  type: conference
  image: https://res.cloudinary.com/dz3zgmhnr/image/upload/v1770667148/3a9a682d-2406-4b20-96e6-dc2e345499df.png
  tags:
    - sea ice
    - cryosphere
    - remote sensing
    - machine learning

#ICESat-2 embeddings
- id: doi:10.1109/IGARSS55030.2025.11242650
  type: conference
  image: https://res.cloudinary.com/dz3zgmhnr/image/upload/v1770666003/b6960440-ff8f-4117-bda4-c49a8226cd74.png
  buttons:
    - type: preprint
      text: preprint
      link: https://arxiv.org/abs/2504.18668
  tags:
    - sea ice
    - cryosphere
    - remote sensing
    - representation learning
    - machine learning

  #ICE-FMBench
- id: doi:10.1145/3764922.3771202
  type: conference
  image: https://res.cloudinary.com/dz3zgmhnr/image/upload/v1770663420/9b9ebc68-4296-4329-bdf7-0974d8c1a317.png
  buttons:
    - type: preprint
      text: preprint
      link: https://arxiv.org/abs/2503.22516v1
  tags:
    - sea ice
    - cryosphere
    - remote sensing
    - foundation model
    - machine learning

#long-form reasoning graph
- id: doi:10.48550/arXiv.2506.01102
  type: conference
  image: https://res.cloudinary.com/dz3zgmhnr/image/upload/v1770663028/d6d78b36-1ed8-469e-b8a1-8af9e0a9ed34.png
  buttons:
    - type: preprint
      text: proceedings
      link: https://openaccess.thecvf.com/content/ICCV2025W/SG2RL/html/Romero_Long-form_Reasoning_for_Keystep_Recognition_using_Graph_Neural_Networks_ICCVW_2025_paper.html
    - type: source
      text: Repo
      link: https://github.com/geohai/graphs-for-keystep-recognition
  tags:
    - spatiotemporal
    - graph neural networks
    - machine learning
    
# PM and location encoding
- id: doi:10.1080/15481603.2025.2594797 
  image: https://res.cloudinary.com/dz3zgmhnr/image/upload/v1750457206/2021-07-05_pred_geoclip_with_boundary_cropped-min-min_r0z2yv.png
  type: journal
  buttons:
    - type: source
      text: Repo
      link: https://github.com/geohai/pm25-geolocation
    - type: preprint
      text: preprint
      link: https://arxiv.org/abs/2505.18461
  tags:
    - spatiotemporal
    - machine learning
    - remote sensing
    - public health
    - air pollution
    - foundation model
    - earth embeddings

#sea ice geolocation
- id: doi:10.1016/j.rsase.2025.101538
  type: journal
  image: https://res.cloudinary.com/dz3zgmhnr/image/upload/v1734926905/e4155d7b-8ddb-4f07-b731-ef5264a10be1.png
  buttons:
    - type: source
      text: Repo
      link: https://github.com/geohai/autoice-challenge-geospatial-encoding
    - type: preprint
      text: preprint
      link: https://eartharxiv.org/repository/view/9036/ 
  tags:
    - sea ice
    - cryosphere
    - remote sensing
    - uncertainty
    - machine learning

#GeoDen
- id: doi:10.1111/cgf.70087
  image:  https://res.cloudinary.com/dz3zgmhnr/image/upload/v1729526913/geoden_zezrd9.jpg
  type: journal
  buttons:
    - type: preprint
      text: preprint
      link: https://arxiv.org/abs/2503.03953 
    - type: source
      text: Repo
      link: https://github.com/geohai/GeoDEN
  tags:
    - spatial analysis
    - visual analytics
    - visualization
    - public health
    - dengue
    - Arbovirus

# Air Pollution PM25
- id: doi:10.3390/rs17010126
  image: https://res.cloudinary.com/dz3zgmhnr/image/upload/v1735849138/remotesensing-17-00126-g004_jk83r3.png
  type: journal
  tags:
    - spatiotemporal
    - machine learning
    - remote sensing
    - public health
    - air pollution

#2024
# sea ice small data regime
- id: doi:10.1109/BigData62323.2024.10825475
  type: proceedings
  image: https://res.cloudinary.com/dz3zgmhnr/image/upload/v1737398804/1a4dcb4f-724e-4d93-ac6e-c6a50f318688.png
  buttons:
    - type: preprint
      text: Full text on ResearchGate
      link: https://www.researchgate.net/publication/388095743_Semi-Supervised_Multi-Source_Sea_Ice_Classification_in_Small-Data_Regime
  tags:
    - sea ice
    - cryosphere
    - remote sensing
    - uncertainty
    - machine learning

#Zika
- id: doi:10.1371/journal.pntd.0012017
  image: images/publication-thumbnails/2024-roell-zika.PNG
  type: journal
  tags:
    - spatial analysis
    - visualization
    - public health
    - Zika
    - Arbovirus

#Partial Label Learning
- id: doi:10.1109/JSTARS.2024.3413003
  type: journal
  image: https://res.cloudinary.com/dz3zgmhnr/image/upload/v1729823147/03984fd1-c25e-473b-a505-03eb03083670.png
  buttons:
    - type: source
      text: Repo
      link: https://github.com/geohai/PLL-sea-ice-classification
  tags:
    - sea ice
    - cryosphere
    - remote sensing
    - uncertainty
    - machine learning

#UCGIS BoK Texts
- id: doi:10.22224/gistbok/2024.1.8
  image: https://res.cloudinary.com/dz3zgmhnr/image/upload/v1729813111/8a99040a-41f0-4bed-b64e-b2b42e44f03e.png
  type: book-chapter
  tags:
    - spatial analysis
    - GIS
    - Natural Language Processing
    - Geographic Information Retrieval
    - machine learning

#2023
#sea ice uncertainty ensemble
- id: doi:10.1109/TGRS.2023.3331276
  type: journal
  image: https://res.cloudinary.com/dz3zgmhnr/image/upload/v1729813611/fig12_wdh7dy_c_pad_w_400_h_400_ultszf.png
  buttons:
    - type: preprint
      link: https://eartharxiv.org/repository/view/6568/
    - type: source
      text: Repo
      link: https://github.com/geohai/sea-ice-segment
  tags:
    - sea ice
    - cryosphere
    - uncertainty
    - remote sensing
    - machine learning

#grid vis NREL
- id: doi:10.1109/energyvis60781.2023.00009
  type: proceedings
  image: https://res.cloudinary.com/dz3zgmhnr/image/upload/v1729803915/da42d74c-6fad-4f80-89af-6140afd2618c.png
  buttons:
    - type: preprint
      link: https://arxiv.org/abs/2308.09153
    - type: source
      text: Repo
      link: https://github.com/isaiahlg/voltage-tiling
  tags:
    - visualization
    - electrical grid
    - renewable energy

# enhancing sea ice with atrous
- id: doi:10.1080/01431161.2023.2248560
  type: journal
  image: https://res.cloudinary.com/dz3zgmhnr/image/upload/v1729813751/5fe09a00-0685-4831-84bd-e81e2f69c177_c_pad_w_400_h_400_lzybli.png
  buttons:
    - type: preprint
      link: https://arxiv.org/abs/2310.17122
    - type: source
      text: Repo
      link: https://github.com/geohai/sea-ice-segment
  tags:
    - sea ice
    - cryosphere
    - remote sensing
    - machine learning

# COVID-19 testing and vaccination accessibility
- id: doi:10.5194/ica-adv-4-12-2023
  type: journal
  image: https://res.cloudinary.com/dz3zgmhnr/image/upload/v1729813943/57a05aab-3225-44b0-b587-0015c76a21ae.png
  tags:
    - spatial analysis
    - covid-19
    - public health
    - epidemiology

# IGARSS increasing AOD coverage
- id: doi:10.1109/igarss52108.2023.10282685
  type: proceedings
  image: https://res.cloudinary.com/dz3zgmhnr/image/upload/v1729814130/7b644572-e37b-4a41-9cb5-5c56f06dfc6f.png
  buttons:
    - type: preprint
      link: https://arxiv.org/abs/2306.07242
  tags:
    - spatiotemporal
    - machine learning
    - remote sensing
    - public health
    - air pollution

# IGARSS loss function
- id: doi:10.1109/igarss52108.2023.10282060
  type: proceedings
  image: https://res.cloudinary.com/dz3zgmhnr/image/upload/v1729814071/2023-karimzadeh-loss_comparison_qayliy.png
  buttons:
    - type: preprint
      link: https://arxiv.org/abs/2310.17135
    - type: source
      text: Repo
      link: https://github.com/geohai/sea-ice-segment
  tags:
    - sea ice
    - cryosphere
    - remote sensing
    - machine learning

# IGARSS transfer learning
- id: doi:10.1109/igarss52108.2023.10281892
  type: proceedings
  image: https://res.cloudinary.com/dz3zgmhnr/image/upload/v1729814345/ce3ddd71-8f9a-4065-b36a-c3dea28b4d18.png
  buttons:
    - type: preprint
      link: https://arxiv.org/abs/2310.17126
    - type: source
      text: Repo
      link: https://github.com/geohai/sea-ice-segment
  tags:
    - sea ice
    - cryosphere
    - remote sensing
    - machine learning

# Urban Health editorial AI
- id: doi:10.1007/s11524-022-00714-7
  type: journal
  image: https://res.cloudinary.com/dz3zgmhnr/image/upload/v1729814446/9fa95c51-d0cb-4e49-b1a3-65d1a682e237.png
  buttons:
    - type: preprint
      text: PubMed Access
      link: https://pubmed.ncbi.nlm.nih.gov/36689140/
  tags:
    - covid-19
    - public health
    - epidemiology
    - spatiotemporal
    - machine learning

#2022
# US COVID-19 forecast hub dataset
- id: doi:10.1038/s41597-022-01517-w
  type: journal
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41597-022-01517-w/MediaObjects/41597_2022_1517_Fig1_HTML.png?as=webp
  buttons:
    - type: website
      text: Website
      link: https://covid19forecasthub.org/
    - type: source
      text: Repo
      link: https://github.com/reichlab/covid19-forecast-hub
  tags:
    - spatiotemporal
    - machine learning
    - covid-19
    - public health
    - epidemiology

# NASA community algorithm
- id: doi:10.5281/ZENODO.6320982
  type: poster
  image: https://res.cloudinary.com/dz3zgmhnr/image/upload/v1729797473/4b471cdd-c89c-4c3c-9846-32b956c6feea.png
  tags:
    - remote sensing
    - machine learning
    - sea ice
    - cryosphere
    - synthetic aperture radar

# covidlstm
- id: doi:10.1007/s41060-021-00295-9
  type: journal
  image: https://res.cloudinary.com/dz3zgmhnr/image/upload/v1729799749/2022-lucas-covidlstm_qwousp.jpg
  buttons:
    - type: preprint
      text: PubMed Access
      link: https://pmc.ncbi.nlm.nih.gov/articles/PMC8760128/
    - type: source
      text: Repo
      link: https://github.com/geohai/covid-lstm
  tags:
    - spatiotemporal
    - machine learning
    - covid-19
    - public health
    - epidemiology

#2021
- id: doi:10.1038/s41467-021-26742-6 # vahedi nature comm human interaction
  type: journal
  image: https://res.cloudinary.com/dz3zgmhnr/image/upload/v1729777169/2020-COVID19_STGXB_q6k3cu.webp
  buttons:
    - type: source
      text: Repo
      link: https://github.com/geohai/COVID19-STGXB
  tags:
    - spatiotemporal
    - machine learning
    - covid-19
    - epidemiology
    - public health

- id: doi:10.6084/M9.FIGSHARE.14772891.V1 # vahedi AUG chuckchi
  type: poster
  image: https://res.cloudinary.com/dz3zgmhnr/image/upload/v1729775459/071ee797-4e26-450e-879f-c26a892644e9.png
  tags:
    - remote sensing
    - machine learning
    - sea ice
    - cryosphere

- id: doi:10.25436/E2B88Q #narcoNLP
  type: proceedings
  image: https://res.cloudinary.com/dz3zgmhnr/image/upload/v1729774456/e71ab003-0f48-4804-a1a1-93ae52173403.png
  buttons:
    - type: source
      text: Repo
      link: https://github.com/geohai/narco_nlp
  tags:
    - text
    - natural language processing
    - Geographic Information Retrieval
    - machine learning

#2020 --local links need replaced
- id: doi:10.1109/vast50239.2020.00012
  image: images/publication-thumbnails/2020-wang-stull.jpg

- id: doi:10.24251/hicss.2020.168
  image: images/publication-thumbnails/2020-wang-routepacking.jpg

- id: doi:10.1037/0000193-008
  image: images/publication-thumbnails/2020-karimzadeh-human-guided-va.jpg
  type: book-chapter
  buttons:
    - type: preprint
      text: Full-Text on ResearchGate
      link: https://www.researchgate.net/publication/342188685_Human-guided_visual_analytics_for_big_data
  tags:
    - visual analytics
    - visualization

- id: doi:10.1109/tvcg.2019.2934266
  image: images/publication-thumbnails/2020-khayat-vassl.jpg

#2019
- id: doi:10.1145/3356471.3365243
  image: images/publication-thumbnails/2019-snyder-city-level.jpg

- id: doi:10.1109/hst47167.2019.9033003
  image: images/publication-thumbnails/2019-snyder-survey.jpg

- id: doi:10.1109/visual.2019.8933619
  image: images/publication-thumbnails/2019-zhao-featureexplorer.jpg

- id: doi:10.5194/ica-abs-1-160-2019
  image: images/publication-thumbnails/2019-karimzadeh-ica-geolocation.jpg

- id: doi:10.1111/cgf.13696
  image: images/publication-thumbnails/2019-Yau-line-graph.jpg

- id: doi:10.3390/ijgi8040161
  image: https://www.mdpi.com/ijgi/ijgi-08-00161/article_deploy/html/images/ijgi-08-00161-g001.png

- id: doi:10.1111/tgis.12510
  image: images/publication-thumbnails/2019-karimzadeh-geotxt.jpg

- id: doi:10.1109/tvcg.2019.2934264
  image: images/publication-thumbnails/2019-khayat-eval.jpg

- id: doi:10.1109/tvcg.2019.2934614
  image: images/publication-thumbnails/2019-snyder-smart.jpg

- id: doi:10.1109/tvcg.2019.2934603
  image: images/publication-thumbnails/2019-zhao-metricsvis.jpg

#2017
- id: doi:10.1080/13658816.2017.1368523
  image: images/publication-thumbnails/2017-wallgrun-corpus.jpg

#2016
- id: doi:10.1145/3003464.3003472
  image: images/publication-thumbnails/2016-karimzadeh-eval.jpg

#2015
- id: doi:10.1145/2837689.2837692
  image: images/publication-thumbnails/2015-wallgrun-relational.jpg

#2014
- id: doi:10.1145/2675354.2675701
  image: images/publication-thumbnails/2014-wallgrun-corpus.jpg

#2013
- id: doi:10.1145/2533888.2533942
  image: images/publication-thumbnails/2013-karimzadeh-geotxt.jpg


# Julia Romero #################################################################################
#2024
- id: doi:10.1145/3638550.3641136
  image: https://res.cloudinary.com/dz3zgmhnr/image/upload/v1729871447/optibreathe-signals_wiopcv.jpg
  type: proceedings
  buttons:
    - type: preprint
      text: Full text on ResearchGate
      link: https://www.researchgate.net/publication/378548392_OptiBreathe_An_Earable-based_PPG_System_for_Continuous_Respiration_Rate_Breathing_Phase_and_Tidal_Volume_Monitoring
  tags:
    - wearable devices

#2022
- id: doi:10.3390/ijerph191912933
  image: https://www.mdpi.com/ijerph/ijerph-19-12933/article_deploy/html/images/ijerph-19-12933-g005.png
  tags:
    - covid-19
    - public health
    - wearable devices

- id: doi:10.3390/s23135879
  image: https://www.mdpi.com/sensors/sensors-23-05879/article_deploy/html/images/sensors-23-05879-g001.png
  tags:
    - public health
    - human behavior
    - wearable devices